language: php
php:
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
before_script:
  - composer install --prefer-source --no-interaction --dev
  - wget https://scrutinizer-ci.com/ocular.phar
script: phpunit --coverage-clover=coverage.clover && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
